# SPDX-FileCopyrightText: 2021 Belcan Advanced Solutions
#
# SPDX-License-Identifier: MIT

services:
   certbot:
    image: certbot/certbot:v1.19.0
    container_name: certbot
    volumes:
      - certbot_data:/etc/letsencrypt
      - certbot_www:/var/www/certbot
      - certbot_lib:/var/lib/letsencrypt
      - certbot_keys:/keys
    networks:
      certbot:
    restart: unless-stopped
    entrypoint: ["/bin/sh"]
    command: ["-ec", "while :; do sleep 1 ; done"]
    deploy:
      resources:
        limits:
          memory: ${CERTBOT_MEMLIMIT}


volumes:
  certbot_data:
  certbot_www:
  certbot_lib:
  certbot_keys:

networks:
  certbot: