# SPDX-FileCopyrightText: 2022 Kaelan Thijs Fouwels <kaelan.thijs@fouwels.com>
#
# SPDX-License-Identifier: MIT
---
services:
  gateway:
    image: caddy:2.6.0-alpine
    container_name: gateway
    restart: unless-stopped
    ports:
      - 443:443
    volumes:
      - gateway_data:/data
    configs:
      - source: gateway_config
        target: /etc/caddy/Caddyfile
      - source: gateway_ca
        target: /etc/caddy/ca.crt
    networks:
      gateway:
      alfresco:
      share:
      git:
    deploy:
      resources:
        limits:
          memory: 0.5gb

volumes:
  gateway_data:

configs:
  gateway_config:
    file: ./config/gateway/Caddyfile
  gateway_ca:
    file: ./config/gateway/ca.crt

networks:
  gateway:
