# SPDX-FileCopyrightText: 2021 Kaelan Thijs Fouwels <kaelan.thijs@fouwels.com>
#
# SPDX-License-Identifier: MIT
---
services:
  git:
    image: gitea/gitea:1.15.9
    container_name: git
    volumes:
      - git_data:/data
      - git_app_data:/app/gitea/data
    configs:
      - source: config
        target: /data/gitea/conf/app.ini
    networks:
      git:
      git-postgres:
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: ${GIT_MEMLIMIT}

configs:
  config:
    file: ./config/git/app.ini

volumes:
  git_data:
  git_app_data:

networks:
  git:
