# SPDX-FileCopyrightText: 2021 Kaelan Thijs Fouwels <kaelan.thijs@fouwels.com>
#
# SPDX-License-Identifier: MIT
---
services:
  solr6:
    container_name: solr6
    image: alfresco/alfresco-search-services:2.0.3
    environment:
      SOLR_ALFRESCO_HOST: alfresco
      SOLR_ALFRESCO_PORT: 8080
      SOLR_SOLR_HOST: solr6
      SOLR_SOLR_PORT: 8983
      SOLR_CREATE_ALFRESCO_DEFAULTS: alfresco,archive
      ALFRESCO_SECURE_COMMS: none
      SOLR_JAVA_MEM: "-Xmx${SOLR_XM}"
      JAVA_OPTS: "
      -Dalfresco.secureComms=secret
      -Dalfresco.secureComms.secret=noauth
      "
    volumes:
      - solr-data:/opt/alfresco-search-services/data
      - solr-keystores:/opt/alfresco-search-services/keystores
      - solr-solrhome:/opt/alfresco-search-services/solrhome
    networks:
      - solr6
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: ${SOLR_MEMLIMIT}

volumes:
  solr-data:
  solr-keystores:
  solr-solrhome:

networks:
  solr6:
