# SPDX-FileCopyrightText: 2021 Kaelan Thijs Fouwels <kaelan.thijs@fouwels.com>
#
# SPDX-License-Identifier: MIT
---
services:
  transforms:
    restart: unless-stopped
    image: alfresco/alfresco-transform-core-aio:2.6.0
    container_name: transforms
    environment:
      JAVA_OPTS: "-Xmx${AIO_XM}"
    networks:
      - transforms
    deploy:
      resources:
        limits:
          memory: ${AIO_MEMLIMIT}

networks:
  transforms:
